# Generated by Django 4.0.4 on 2022-05-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
